# Assignment 1: Web Scraping

In all the following questions, you have to use BeautifulSoup to scrape different websites and
collect data as per the requirement of the question.

In [32]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

1) Write a python program to display all the header tags from wikipedia.org.

In [35]:
def get_header_tags(url):
    page=requests.get(url)
    soup=BeautifulSoup(page.content,'html.parser')
    titles=[]
    tags=['h1','h2','h3','h4','h5','h6']
    for i in soup.find_all(tags):
        titles.append(i.text)
    return titles
url='https://en.wikipedia.org/wiki/Main_Page'
get_header_tags(url)

['Main Page',
 'Welcome to Wikipedia',
 "From today's featured article",
 'Did you know\xa0...',
 'In the news',
 'On this day',
 "Today's featured picture",
 'Other areas of Wikipedia',
 "Wikipedia's sister projects",
 'Wikipedia languages']

2) Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year
of release) and make data frame.

In [34]:
def get_100_movies(url):
    page=requests.get(url)
    soup=BeautifulSoup(page.content, 'html.parser')
    titles=[]
    years=[]
    ratings=[]
    for i in soup.find_all('h3', class_='lister-item-header'):
        titles.append(i.find('a').text.strip())
    for i in soup.find_all('span', class_='lister-item-year'):
        year_text=i.text.strip()
        year = re.search(r'\d{4}', year_text).group()
        years.append(year)
    ratings=[]
    for i in soup.find_all('div', class_='ipl-rating-star small'):
        rating = i.find('span', class_="ipl-rating-star__rating").text.strip()
        ratings.append(rating)
    df=pd.DataFrame({'Name':titles,'Rating':ratings,'Year of Release':years})
    return df

imdb_url = 'https://www.imdb.com/list/ls004139640/'
get_100_movies(imdb_url)

                            Name Rating Year of Release
0                  The Godfather    9.2            1972
1                         Psycho    8.5            1960
2                    Rear Window    8.5            1954
3                   Mystic River    7.9            2003
4                    Taxi Driver    8.2            1976
..                           ...    ...             ...
95                     Nosferatu    7.9            1922
96                      Gaslight    7.8            1944
97                     King Kong    7.9            1933
98       The Woman in the Window    7.6            1944
99  Es geschah am hellichten Tag    7.8            1958

[100 rows x 3 columns]

3) Write a python program to scrape mentioned details from dineout.co.in: i) Restaurant name
ii) Cuisine iii) Location iv) Ratings v) Image URL.

In [36]:
def get_restaurants(url):
    page=requests.get(url)
    soup=BeautifulSoup(page.content, 'html.parser')
    names=[]
    cuisine=[]
    locs=[]
    ratings=[]
    img_urls=[]
    for i in soup.find_all('a', class_='restnt-name ellipsis'):
        names.append(i.text)
    for i in soup.find_all('div',class_='img-wrap'):
        ratings.append(i.find('div',class_='restnt-rating').text)
    for i in soup.find_all('img', class_="no-img"):
        img_urls.append(i['data-src'])
    for i in soup.find_all('div', class_='restnt-loc ellipsis'):
        locs.append(i.text.strip())
    for i in soup.find_all('span', class_='double-line-ellipsis'):
        a=[]
        for j in i.find_all('a'):
            a.append(j.text)
        cuisine.append(a)
    df=pd.DataFrame({'Restaurant Name':names,'Cuisines':cuisine,'Location':locs,'Rating':ratings,'Image urls':img_urls})
    return df
url="https://www.dineout.co.in/hyderabad-restaurants/trending"
get_restaurants(url)

,Restaurant Name,Cuisines,Location,Rating,Image urls
0,Verandah,"[Chinese, North Indian, Continental, Italian]","The Park,Somajiguda, Central East Hyderabad",3.9,https://im1.dineout.co.in/images/uploads/resta...
1,Subway,[Fast Food],"Somajiguda, Central East Hyderabad",3.4,https://im1.dineout.co.in/images/uploads/resta...
2,Subway,[Fast Food],"Khairatabad, Central Hyderabad",3.5,https://im1.dineout.co.in/images/uploads/resta...
3,Subway,[Fast Food],"Mayfair Complex,SP Road, Secunderabad",4.8,https://im1.dineout.co.in/images/uploads/resta...
4,Cream Stone,"[Desserts, Beverages]","Banjara Hills, Central East Hyderabad",4.3,https://im1.dineout.co.in/images/uploads/resta...
5,Cream Stone,"[Desserts, Beverages]","SP Road, Secunderabad",4.5,https://im1.dineout.co.in/images/uploads/resta...
6,Tabla,"[North Indian, Chinese, Andhra]","Bhaskar Plaza,Banjara Hills, Central East Hyde...",4.1,https://im1.dineout.co.in/images/uploads/resta...
7,Bikanervala,"[North Indian, Street Food, Fast Food]","Banjara Hills, Central East Hyderabad",4.2,https://im1.dineout.co.in/images/uploads/resta...
8,Curry Pot,"[North Indian, Chinese, South Indian]","PG Road, Secunderabad",4.3,https://im1.dineout.co.in/images/uploads/resta...
9,Ocean's Basket,"[Continental, Chinese, North Indian, South Ind...","Banjara Hills, Central East Hyderabad",4.4,https://im1.dineout.co.in/images/uploads/resta...
10,Subway,[Fast Food],"GVK One Mall,Banjara Hills, Central East Hyder...",2.8,https://im1.dineout.co.in/images/uploads/resta...
11,Rayalaseema Ruchulu,"[Andhra, South Indian, North Indian]","Lakdi-Ka-Pul, Central Hyderabad",4,https://im1.dineout.co.in/images/uploads/resta...
12,Chill & Terrace,"[North Indian, Continental, South Indian]","Radisson Blu Plaza Hotel,Banjara Hills, Centra...",3.9,https://im1.dineout.co.in/images/uploads/resta...
13,Masala Republic,"[Continental, Chinese, North Indian, Fusion, S...","Himayath Nagar, Central Hyderabad",4,https://im1.dineout.co.in/images/uploads/resta...
14,A'La Liberty,"[North Indian, Chinese, Mexican]","Leela Gopal Towers,Banjara Hills, Central East...",4.1,https://im1.dineout.co.in/images/uploads/resta...
15,Cream Stone,"[Desserts, Beverages]","The Platinum Hotel,Himayath Nagar, Central Hyd...",4.3,https://im1.dineout.co.in/images/uploads/resta...
16,A Bleu Basil,"[Chinese, North Indian, Fast Food, Street Food]","Far East Plaza,Himayath Nagar, Central Hyderabad",4.2,https://im1.dineout.co.in/images/uploads/resta...
17,Salt & Pepper,"[North Indian, Chinese, Continental, Awadhi]","The Central Court Hotel,Lakdi-Ka-Pul, Central ...",2.9,https://im1.dineout.co.in/images/uploads/resta...
18,Exotica,"[North Indian, Chinese, Asian]","12th Square Building,Banjara Hills, Central Ea...",4.3,https://im1.dineout.co.in/images/uploads/resta...
19,Reshmi's Classic Restaurant,"[North Indian, Chinese]","SD Road, Secunderabad",4,https://im1.dineout.co.in/images/uploads/resta...
20,Bikanervala,"[North Indian, Street Food, Fast Food, Dessert...","Basheerbagh, Central Hyderabad",4.2,https://im1.dineout.co.in/images/uploads/resta...

4) Write s python program to display list of respected former finance minister of India(i.e.
Name , Term of office) from https://presidentofindia.nic.in/former-presidents.htm and make
data frame.

In [40]:
def get_ffm(url):
    page=requests.get(url)
    soup=BeautifulSoup(page.content, 'html.parser')
    table=soup.find('table')
    names=[]
    terms=[] 
    if table:
            rows=table.find_all('tr')
            for row in rows[1:]:  
                    cells=row.find_all('td')
                    if len(cells)>=2:  
                            name=cells[2].text.strip()
                            term=cells[1].text.strip()
                            names.append(name)
                            terms.append(term)
    df=pd.DataFrame({'Name':names,'Term of office':terms})
    return df
url='https://www.dor.gov.in/fm-independence'
get_ffm(url)

                          Name Term of office
0            Shri Arun Jaitley           2014
1               P. Chidambaram      2012-2014
2             Pranab Mukherjee      2009-2012
3               P. Chidambaram        2004-08
4                Jaswant Singh        2002-04
5                Yaswant Sinha        1998-02
6               P. Chidambaram        1996-98
7                Jaswant Singh           1996
8           Dr. Manmohan Singh        1991-96
9               Yashwant Sinha        1990-91
10             Madhu Dandavate        1989-90
11                 S.B. Chavan        1988-89
12                 N.D. Tiwari        1987-88
13          Rajiv Gandhi, P.M.           1987
14                  V.P. Singh        1984-86
15            Pranab Mukherjee        1982-84
16             R. Venkataraman        1980-82
17               H.N. Bahuguna           1979
18      Charan Singh, Dy. P.M.           1979
19                  H.M. Patel        1977-78
20              C. Subramanian        1975-77
21                 Y.B. Chavan        1971-74
22    Smt. Indira Gandhi, P.M.        1969-70
23  Morarji R. Desai, Dy. P.M.        1967-69
24            Sachin Choudhury        1966-67
25         T.T. Krishnamachari        1964-65
26            Morarji R. Desai        1959-64
27     Jawahar Lal Nehru, P.M.        1958-59
28         T.T. Krishnamachari        1957-58
29           Dr. C.D. Deshmukh        1951-57
30             Dr. John Mathai        1950-51
31      R.K. Shanmukham Chetty        1947-49
32            Liaquat Ali Khan           1947