In [3]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import pandas as pd
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
import requests

1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url
= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: A)
Rank
B) Name
C) Artist
D) Upload date
E) Views

In [110]:
driver=webdriver.Chrome()

In [111]:
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [122]:
wait = WebDriverWait(driver, 10)
table = wait.until(EC.presence_of_element_located((By.XPATH, '//table[@class="wikitable sortable jquery-tablesorter"]')))
rows = table.find_elements(By.TAG_NAME, 'tr')
most_viewed_videos = []
for row in rows:
    columns = row.find_elements(By.TAG_NAME, 'td')
    rank=columns[0].text.strip()
print(rank)

IndexError: list index out of range

2. Scrape the details team Indiaâ€™s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Series
B) Place
C) Date
D) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get("https://www.bcci.tv/")

In [5]:
destination=driver.find_element(By.XPATH,"/html/body/header/div[3]/div[2]/ul/div[1]/a[2]")

In [6]:
destination.click()

In [17]:
series=[]
places=[]
dates=[]
time=[]
stags=driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
for i in stags:
    series.append(i.text.strip())
placetags=driver.find_elements(By.XPATH,'//div[@class="match-place ng-scope"]/span[2]')
for i in placetags:
    places.append(i.text.strip())
datetags=driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
for i in datetags:
    dates.append(i.text.strip())
timetags=driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
for i in timetags:
    time.append(i.text.strip())

In [19]:
df=pd.DataFrame({'Series':series,'Place':places,'Date':dates,'Time':time})
df

                        Series     Place           Date         Time
0  ICC MENS T20 WORLD CUP 2024  New York   5 JUNE, 2024  8:00 PM IST
1  ICC MENS T20 WORLD CUP 2024  New York   9 JUNE, 2024  8:00 PM IST
2  ICC MENS T20 WORLD CUP 2024  New York  12 JUNE, 2024  8:00 PM IST
3  ICC MENS T20 WORLD CUP 2024   Florida  15 JUNE, 2024  8:00 PM IST
4  INDIA TOUR OF ZIMBABWE 2024    Harare   6 JULY, 2024  8:00 PM IST
5  INDIA TOUR OF ZIMBABWE 2024    Harare   7 JULY, 2024  8:00 PM IST
6  INDIA TOUR OF ZIMBABWE 2024    Harare  10 JULY, 2024  8:00 PM IST
7  INDIA TOUR OF ZIMBABWE 2024    Harare  13 JULY, 2024  8:00 PM IST
8  INDIA TOUR OF ZIMBABWE 2024    Harare  14 JULY, 2024  8:00 PM IST

In [20]:
driver.quit()

3. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details: A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [21]:
driver=webdriver.Chrome()

In [22]:
driver.get("http://statisticstimes.com/")

In [23]:
driver.quit()

4. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [83]:
driver=webdriver.Chrome()

In [84]:
driver.get("https://github.com/")

In [85]:
opensources=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button")
opensources.click()

In [86]:
trending=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a")

In [87]:
trending.click()

In [107]:
rtitles=[]
rnametags=driver.find_elements(By.XPATH,'//span[@class="text-normal"]')
for i in rnametags:
    rtitles.append(i.text.strip(' /'))
rdescs=[]
rcount=[]
languages=[]
rcountags=driver.find_elements(By.XPATH,'//a[2][@class="Link Link--muted d-inline-block mr-3"]')
for i in rcountags:
    rcount.append(i.text.strip())
rdesctags = driver.find_elements(By.XPATH, '//article[@class="Box-row"]')
for i in rdesctags:
    try:
        if i.find_element(By.XPATH,'//p[@class="col-9 text-gray my-1 pr-4"]'):
            r=i.find_element(By.XPATH,'//p[@class="col-9 text-gray my-1 pr-4"]')
            rdescs.append(r.text.strip())
    except NoSuchElementException:
        rdescs.append('-')
langtags = driver.find_elements(By.XPATH, '//div[@class="f6 color-fg-muted mt-2"]')
for i in langtags:
    try:
        if i.find_element(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]/span[2]'):
            l=i.find_element(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]/span[2]')
            languages.append(l.text.strip())
    except NoSuchElementException:
        languages.append('-')

In [109]:
driver.quit()

5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the
following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
 Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [55]:
driver=webdriver.Chrome()

In [56]:
driver.get("https:/www.billboard.com/")

In [58]:
charts=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[1]/div/div/div[2]/div/nav/ul/li[1]/a')
charts.click()

In [60]:
top100=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a')
top100.click()

In [77]:
names=[]
nametags=driver.find_elements(By.XPATH,'//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]')
for i in nametags:
    names.append(i.text.strip())
artists=[]
artistags=driver.find_elements(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]')
for i in artistags:
    artists.append(i.text.strip())
lwrprwb=[]
lwrtags=driver.find_elements(By.XPATH,'//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]') 
for i in lwrtags:
    lwrprwb.append(i.text.strip(''))

In [79]:
ranks = [num for num in lwrprwb if num]

lwr=ranks[::3]
pr=ranks[1::3]
wb=ranks[2::3]

In [81]:
df=pd.DataFrame({'Name':names,'Artist':artists,'Last Week Rank':lwr,'Peak Rank':pr,'Weeks on board':wb})
df

,Name,Artist,Last Week Rank,Peak Rank,Weeks on board
0,Type Shit,"Future, Metro Boomin, Travis Scott & Playboi C...",-,2,1
1,Beautiful Things,Benson Boone,2,2,10
2,Lose Control,Teddy Swims,1,1,33
3,Too Sweet,Hozier,-,5,1
4,Cinderella,"Future, Metro Boomin & Travis Scott",-,6,1
...,...,...,...,...,...
94,La Victima,Xavi,77,46,15
95,Tucson Too Late,Jordan Davis,81,81,4
96,Empire Now,Hozier,-,98,1
97,Girl I've Always Been,Olivia Rodrigo,-,99,1
98,Outskirts,Sam Hunt,92,92,3

In [82]:
driver.quit()

6. Scrape the details of Highest selling novels.
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre
 Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [13]:
driver=webdriver.Chrome()

In [14]:
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [30]:
table = driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[2]/div/div[2]/div/table')
ranks=[]
book_names=[]
author_names=[]
volumes_sold=[]
publishers=[]
genres=[]
rows = table.find_elements(By.TAG_NAME, "tr")
for row in rows[2:]:
    columns = row.find_elements(By.TAG_NAME, "td")
    ranks.append(columns[0].text)
    book_names.append(columns[1].text)
    author_names.append(columns[2].text)
    volumes_sold.append(columns[3].text)
    publishers.append(columns[4].text)
    genres.append(columns[5].text)

In [34]:
for i in range(len(book_names)):
    print("Book Name:",book_names[i])
    print("Author Name:",author_names[i])
    print("Volumes Sold:",volumes_sold[i])
    print("Publisher:",publishers[i])
    print("Genre:",genres[i])
    print()

Book Name: 1
Author Name: Da Vinci Code,The
Volumes Sold: Brown, Dan
Publisher: 5,094,805
Genre: Transworld

Book Name: 2
Author Name: Harry Potter and the Deathly Hallows
Volumes Sold: Rowling, J.K.
Publisher: 4,475,152
Genre: Bloomsbury

Book Name: 3
Author Name: Harry Potter and the Philosopher's Stone
Volumes Sold: Rowling, J.K.
Publisher: 4,200,654
Genre: Bloomsbury

Book Name: 4
Author Name: Harry Potter and the Order of the Phoenix
Volumes Sold: Rowling, J.K.
Publisher: 4,179,479
Genre: Bloomsbury

Book Name: 5
Author Name: Fifty Shades of Grey
Volumes Sold: James, E. L.
Publisher: 3,758,936
Genre: Random House

Book Name: 6
Author Name: Harry Potter and the Goblet of Fire
Volumes Sold: Rowling, J.K.
Publisher: 3,583,215
Genre: Bloomsbury

Book Name: 7
Author Name: Harry Potter and the Chamber of Secrets
Volumes Sold: Rowling, J.K.
Publisher: 3,484,047
Genre: Bloomsbury

Book Name: 8
Author Name: Harry Potter and the Prisoner of Azkaban
Volumes Sold: Rowling, J.K.
Publisher: 3,377,906
Genre: Bloomsbury

Book Name: 9
Author Name: Angels and Demons
Volumes Sold: Brown, Dan
Publisher: 3,193,946
Genre: Transworld

Book Name: 10
Author Name: Harry Potter and the Half-blood Prince:Children's Edition
Volumes Sold: Rowling, J.K.
Publisher: 2,950,264
Genre: Bloomsbury

Book Name: 11
Author Name: Fifty Shades Darker
Volumes Sold: James, E. L.
Publisher: 2,479,784
Genre: Random House

Book Name: 12
Author Name: Twilight
Volumes Sold: Meyer, Stephenie
Publisher: 2,315,405
Genre: Little, Brown Book

Book Name: 13
Author Name: Girl with the Dragon Tattoo,The:Millennium Trilogy
Volumes Sold: Larsson, Stieg
Publisher: 2,233,570
Genre: Quercus

Book Name: 14
Author Name: Fifty Shades Freed
Volumes Sold: James, E. L.
Publisher: 2,193,928
Genre: Random House

Book Name: 15
Author Name: Lost Symbol,The
Volumes Sold: Brown, Dan
Publisher: 2,183,031
Genre: Transworld

Book Name: 16
Author Name: New Moon
Volumes Sold: Meyer, Stephenie
Publisher: 2,152,737
Genre: Little, Brown Book

Book Name: 17
Author Name: Deception Point
Volumes Sold: Brown, Dan
Publisher: 2,062,145
Genre: Transworld

Book Name: 18
Author Name: Eclipse
Volumes Sold: Meyer, Stephenie
Publisher: 2,052,876
Genre: Little, Brown Book

Book Name: 19
Author Name: Lovely Bones,The
Volumes Sold: Sebold, Alice
Publisher: 2,005,598
Genre: Pan Macmillan

Book Name: 20
Author Name: Curious Incident of the Dog in the Night-time,The
Volumes Sold: Haddon, Mark
Publisher: 1,979,552
Genre: Random House

Book Name: 21
Author Name: Digital Fortress
Volumes Sold: Brown, Dan
Publisher: 1,928,900
Genre: Transworld

Book Name: 22
Author Name: Short History of Nearly Everything,A
Volumes Sold: Bryson, Bill
Publisher: 1,852,919
Genre: Transworld

Book Name: 23
Author Name: Girl Who Played with Fire,The:Millennium Trilogy
Volumes Sold: Larsson, Stieg
Publisher: 1,814,784
Genre: Quercus

Book Name: 24
Author Name: Breaking Dawn
Volumes Sold: Meyer, Stephenie
Publisher: 1,787,118
Genre: Little, Brown Book

Book Name: 25
Author Name: Very Hungry Caterpillar,The:The Very Hungry Caterpillar
Volumes Sold: Carle, Eric
Publisher: 1,783,535
Genre: Penguin

Book Name: 26
Author Name: Gruffalo,The
Volumes Sold: Donaldson, Julia
Publisher: 1,781,269
Genre: Pan Macmillan

Book Name: 27
Author Name: Jamie's 30-Minute Meals
Volumes Sold: Oliver, Jamie
Publisher: 1,743,266
Genre: Penguin

Book Name: 28
Author Name: Kite Runner,The
Volumes Sold: Hosseini, Khaled
Publisher: 1,629,119
Genre: Bloomsbury

Book Name: 29
Author Name: One Day
Volumes Sold: Nicholls, David
Publisher: 1,616,068
Genre: Hodder & Stoughton

Book Name: 30
Author Name: Thousand Splendid Suns,A
Volumes Sold: Hosseini, Khaled
Publisher: 1,583,992
Genre: Bloomsbury

Book Name: 31
Author Name: Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy
Volumes Sold: Larsson, Stieg
Publisher: 1,555,135
Genre: Quercus

Book Name: 32
Author Name: Time Traveler's Wife,The
Volumes Sold: Niffenegger, Audrey
Publisher: 1,546,886
Genre: Random House

Book Name: 33
Author Name: Atonement
Volumes Sold: McEwan, Ian
Publisher: 1,539,428
Genre: Random House

Book Name: 34
Author Name: Bridget Jones's Diary:A Novel
Volumes Sold: Fielding, Helen
Publisher: 1,508,205
Genre: Pan Macmillan

Book Name: 35
Author Name: World According to Clarkson,The
Volumes Sold: Clarkson, Jeremy
Publisher: 1,489,403
Genre: Penguin

Book Name: 36
Author Name: Captain Corelli's Mandolin
Volumes Sold: Bernieres, Louis de
Publisher: 1,352,318
Genre: Random House

Book Name: 37
Author Name: Sound of Laughter,The
Volumes Sold: Kay, Peter
Publisher: 1,310,207
Genre: Random House

Book Name: 38
Author Name: Life of Pi
Volumes Sold: Martel, Yann
Publisher: 1,310,176
Genre: Canongate

Book Name: 39
Author Name: Billy Connolly
Volumes Sold: Stephenson, Pamela
Publisher: 1,231,957
Genre: HarperCollins

Book Name: 40
Author Name: Child Called It,A
Volumes Sold: Pelzer, Dave
Publisher: 1,217,712
Genre: Orion

Book Name: 41
Author Name: Gruffalo's Child,The
Volumes Sold: Donaldson, Julia
Publisher: 1,208,711
Genre: Pan Macmillan

Book Name: 42
Author Name: Angela's Ashes:A Memoir of a Childhood
Volumes Sold: McCourt, Frank
Publisher: 1,204,058
Genre: HarperCollins

Book Name: 43
Author Name: Birdsong
Volumes Sold: Faulks, Sebastian
Publisher: 1,184,967
Genre: Random House

Book Name: 44
Author Name: Northern Lights:His Dark Materials S.
Volumes Sold: Pullman, Philip
Publisher: 1,181,503
Genre: Scholastic Ltd.

Book Name: 45
Author Name: Labyrinth
Volumes Sold: Mosse, Kate
Publisher: 1,181,093
Genre: Orion

Book Name: 46
Author Name: Harry Potter and the Half-blood Prince
Volumes Sold: Rowling, J.K.
Publisher: 1,153,181
Genre: Bloomsbury

Book Name: 47
Author Name: Help,The
Volumes Sold: Stockett, Kathryn
Publisher: 1,132,336
Genre: Penguin

Book Name: 48
Author Name: Man and Boy
Volumes Sold: Parsons, Tony
Publisher: 1,130,802
Genre: HarperCollins

Book Name: 49
Author Name: Memoirs of a Geisha
Volumes Sold: Golden, Arthur
Publisher: 1,126,337
Genre: Random House

Book Name: 50
Author Name: No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.
Volumes Sold: McCall Smith, Alexander
Publisher: 1,115,549
Genre: Little, Brown Book

Book Name: 51
Author Name: Island,The
Volumes Sold: Hislop, Victoria
Publisher: 1,108,328
Genre: Headline

Book Name: 52
Author Name: PS, I Love You
Volumes Sold: Ahern, Cecelia
Publisher: 1,107,379
Genre: HarperCollins

Book Name: 53
Author Name: You are What You Eat:The Plan That Will Change Your Life
Volumes Sold: McKeith, Gillian
Publisher: 1,104,403
Genre: Penguin

Book Name: 54
Author Name: Shadow of the Wind,The
Volumes Sold: Zafon, Carlos Ruiz
Publisher: 1,092,349
Genre: Orion

Book Name: 55
Author Name: Tales of Beedle the Bard,The
Volumes Sold: Rowling, J.K.
Publisher: 1,090,847
Genre: Bloomsbury

Book Name: 56
Author Name: Broker,The
Volumes Sold: Grisham, John
Publisher: 1,087,262
Genre: Random House

Book Name: 57
Author Name: Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P
Volumes Sold: Atkins, Robert C.
Publisher: 1,054,196
Genre: Random House

Book Name: 58
Author Name: Subtle Knife,The:His Dark Materials S.
Volumes Sold: Pullman, Philip
Publisher: 1,037,160
Genre: Scholastic Ltd.

Book Name: 59
Author Name: Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation
Volumes Sold: Truss, Lynne
Publisher: 1,023,688
Genre: Profile Books Group

Book Name: 60
Author Name: Delia's How to Cook:(Bk.1)
Volumes Sold: Smith, Delia
Publisher: 1,015,956
Genre: Random House

Book Name: 61
Author Name: Chocolat
Volumes Sold: Harris, Joanne
Publisher: 1,009,873
Genre: Transworld

Book Name: 62
Author Name: Boy in the Striped Pyjamas,The
Volumes Sold: Boyne, John
Publisher: 1,004,414
Genre: Random House Childrens Books G

Book Name: 63
Author Name: My Sister's Keeper
Volumes Sold: Picoult, Jodi
Publisher: 1,003,780
Genre: Hodder & Stoughton

Book Name: 64
Author Name: Amber Spyglass,The:His Dark Materials S.
Volumes Sold: Pullman, Philip
Publisher: 1,002,314
Genre: Scholastic Ltd.

Book Name: 65
Author Name: To Kill a Mockingbird
Volumes Sold: Lee, Harper
Publisher: 998,213
Genre: Random House

Book Name: 66
Author Name: Men are from Mars, Women are from Venus:A Practical Guide for Improvin
Volumes Sold: Gray, John
Publisher: 992,846
Genre: HarperCollins

Book Name: 67
Author Name: Dear Fatty
Volumes Sold: French, Dawn
Publisher: 986,753
Genre: Random House

Book Name: 68
Author Name: Short History of Tractors in Ukrainian,A
Volumes Sold: Lewycka, Marina
Publisher: 986,115
Genre: Penguin

Book Name: 69
Author Name: Hannibal
Volumes Sold: Harris, Thomas
Publisher: 970,509
Genre: Random House

Book Name: 70
Author Name: Lord of the Rings,The
Volumes Sold: Tolkien, J. R. R.
Publisher: 967,466
Genre: HarperCollins

Book Name: 71
Author Name: Stupid White Men:...and Other Sorry Excuses for the State of the Natio
Volumes Sold: Moore, Michael
Publisher: 963,353
Genre: Penguin

Book Name: 72
Author Name: Interpretation of Murder,The
Volumes Sold: Rubenfeld, Jed
Publisher: 962,515
Genre: Headline

Book Name: 73
Author Name: Sharon Osbourne Extreme:My Autobiography
Volumes Sold: Osbourne, Sharon
Publisher: 959,496
Genre: Little, Brown Book

Book Name: 74
Author Name: Alchemist,The:A Fable About Following Your Dream
Volumes Sold: Coelho, Paulo
Publisher: 956,114
Genre: HarperCollins

Book Name: 75
Author Name: At My Mother's Knee ...:and Other Low Joints
Volumes Sold: O'Grady, Paul
Publisher: 945,640
Genre: Transworld

Book Name: 76
Author Name: Notes from a Small Island
Volumes Sold: Bryson, Bill
Publisher: 931,312
Genre: Transworld

Book Name: 77
Author Name: Return of the Naked Chef,The
Volumes Sold: Oliver, Jamie
Publisher: 925,425
Genre: Penguin

Book Name: 78
Author Name: Bridget Jones: The Edge of Reason
Volumes Sold: Fielding, Helen
Publisher: 924,695
Genre: Pan Macmillan

Book Name: 79
Author Name: Jamie's Italy
Volumes Sold: Oliver, Jamie
Publisher: 906,968
Genre: Penguin

Book Name: 80
Author Name: I Can Make You Thin
Volumes Sold: McKenna, Paul
Publisher: 905,086
Genre: Transworld

Book Name: 81
Author Name: Down Under
Volumes Sold: Bryson, Bill
Publisher: 890,847
Genre: Transworld

Book Name: 82
Author Name: Summons,The
Volumes Sold: Grisham, John
Publisher: 869,671
Genre: Random House

Book Name: 83
Author Name: Small Island
Volumes Sold: Levy, Andrea
Publisher: 869,659
Genre: Headline

Book Name: 84
Author Name: Nigella Express
Volumes Sold: Lawson, Nigella
Publisher: 862,602
Genre: Random House

Book Name: 85
Author Name: Brick Lane
Volumes Sold: Ali, Monica
Publisher: 856,540
Genre: Transworld

Book Name: 86
Author Name: Memory Keeper's Daughter,The
Volumes Sold: Edwards, Kim
Publisher: 845,858
Genre: Penguin

Book Name: 87
Author Name: Room on the Broom
Volumes Sold: Donaldson, Julia
Publisher: 842,535
Genre: Pan Macmillan

Book Name: 88
Author Name: About a Boy
Volumes Sold: Hornby, Nick
Publisher: 828,215
Genre: Penguin

Book Name: 89
Author Name: My Booky Wook
Volumes Sold: Brand, Russell
Publisher: 820,563
Genre: Hodder & Stoughton

Book Name: 90
Author Name: God Delusion,The
Volumes Sold: Dawkins, Richard
Publisher: 816,907
Genre: Transworld

Book Name: 91
Author Name: "Beano" Annual,The
Volumes Sold: 0
Publisher: 816,585
Genre: D.C. Thomson

Book Name: 92
Author Name: White Teeth
Volumes Sold: Smith, Zadie
Publisher: 815,586
Genre: Penguin

Book Name: 93
Author Name: House at Riverton,The
Volumes Sold: Morton, Kate
Publisher: 814,370
Genre: Pan Macmillan

Book Name: 94
Author Name: Book Thief,The
Volumes Sold: Zusak, Markus
Publisher: 809,641
Genre: Transworld

Book Name: 95
Author Name: Nights of Rain and Stars
Volumes Sold: Binchy, Maeve
Publisher: 808,900
Genre: Orion

Book Name: 96
Author Name: Ghost,The
Volumes Sold: Harris, Robert
Publisher: 807,311
Genre: Random House

Book Name: 97
Author Name: Happy Days with the Naked Chef
Volumes Sold: Oliver, Jamie
Publisher: 794,201
Genre: Penguin

Book Name: 98
Author Name: Hunger Games,The:Hunger Games Trilogy
Volumes Sold: Collins, Suzanne
Publisher: 792,187
Genre: Scholastic Ltd.

Book Name: 99
Author Name: Lost Boy,The:A Foster Child's Search for the Love of a Family
Volumes Sold: Pelzer, Dave
Publisher: 791,507
Genre: Orion

Book Name: 100
Author Name: Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours
Volumes Sold: Oliver, Jamie
Publisher: 791,095
Genre: Penguin

Book Name: Da Vinci Code,The
Author Name: Brown, Dan
Volumes Sold: 5,094,805
Publisher: Transworld
Genre: Crime, Thriller & Adventure

Book Name: Harry Potter and the Deathly Hallows
Author Name: Rowling, J.K.
Volumes Sold: 4,475,152
Publisher: Bloomsbury
Genre: Children's Fiction

Book Name: Harry Potter and the Philosopher's Stone
Author Name: Rowling, J.K.
Volumes Sold: 4,200,654
Publisher: Bloomsbury
Genre: Children's Fiction

Book Name: Harry Potter and the Order of the Phoenix
Author Name: Rowling, J.K.
Volumes Sold: 4,179,479
Publisher: Bloomsbury
Genre: Children's Fiction

Book Name: Fifty Shades of Grey
Author Name: James, E. L.
Volumes Sold: 3,758,936
Publisher: Random House
Genre: Romance & Sagas

Book Name: Harry Potter and the Goblet of Fire
Author Name: Rowling, J.K.
Volumes Sold: 3,583,215
Publisher: Bloomsbury
Genre: Children's Fiction

Book Name: Harry Potter and the Chamber of Secrets
Author Name: Rowling, J.K.
Volumes Sold: 3,484,047
Publisher: Bloomsbury
Genre: Children's Fiction

Book Name: Harry Potter and the Prisoner of Azkaban
Author Name: Rowling, J.K.
Volumes Sold: 3,377,906
Publisher: Bloomsbury
Genre: Children's Fiction

Book Name: Angels and Demons
Author Name: Brown, Dan
Volumes Sold: 3,193,946
Publisher: Transworld
Genre: Crime, Thriller & Adventure

Book Name: Harry Potter and the Half-blood Prince:Children's Edition
Author Name: Rowling, J.K.
Volumes Sold: 2,950,264
Publisher: Bloomsbury
Genre: Children's Fiction

Book Name: Fifty Shades Darker
Author Name: James, E. L.
Volumes Sold: 2,479,784
Publisher: Random House
Genre: Romance & Sagas

Book Name: Twilight
Author Name: Meyer, Stephenie
Volumes Sold: 2,315,405
Publisher: Little, Brown Book
Genre: Young Adult Fiction

Book Name: Girl with the Dragon Tattoo,The:Millennium Trilogy
Author Name: Larsson, Stieg
Volumes Sold: 2,233,570
Publisher: Quercus
Genre: Crime, Thriller & Adventure

Book Name: Fifty Shades Freed
Author Name: James, E. L.
Volumes Sold: 2,193,928
Publisher: Random House
Genre: Romance & Sagas

Book Name: Lost Symbol,The
Author Name: Brown, Dan
Volumes Sold: 2,183,031
Publisher: Transworld
Genre: Crime, Thriller & Adventure

Book Name: New Moon
Author Name: Meyer, Stephenie
Volumes Sold: 2,152,737
Publisher: Little, Brown Book
Genre: Young Adult Fiction

Book Name: Deception Point
Author Name: Brown, Dan
Volumes Sold: 2,062,145
Publisher: Transworld
Genre: Crime, Thriller & Adventure

Book Name: Eclipse
Author Name: Meyer, Stephenie
Volumes Sold: 2,052,876
Publisher: Little, Brown Book
Genre: Young Adult Fiction

Book Name: Lovely Bones,The
Author Name: Sebold, Alice
Volumes Sold: 2,005,598
Publisher: Pan Macmillan
Genre: General & Literary Fiction

Book Name: Curious Incident of the Dog in the Night-time,The
Author Name: Haddon, Mark
Volumes Sold: 1,979,552
Publisher: Random House
Genre: General & Literary Fiction

Book Name: Digital Fortress
Author Name: Brown, Dan
Volumes Sold: 1,928,900
Publisher: Transworld
Genre: Crime, Thriller & Adventure

Book Name: Short History of Nearly Everything,A
Author Name: Bryson, Bill
Volumes Sold: 1,852,919
Publisher: Transworld
Genre: Popular Science

Book Name: Girl Who Played with Fire,The:Millennium Trilogy
Author Name: Larsson, Stieg
Volumes Sold: 1,814,784
Publisher: Quercus
Genre: Crime, Thriller & Adventure

Book Name: Breaking Dawn
Author Name: Meyer, Stephenie
Volumes Sold: 1,787,118
Publisher: Little, Brown Book
Genre: Young Adult Fiction

Book Name: Very Hungry Caterpillar,The:The Very Hungry Caterpillar
Author Name: Carle, Eric
Volumes Sold: 1,783,535
Publisher: Penguin
Genre: Picture Books

Book Name: Gruffalo,The
Author Name: Donaldson, Julia
Volumes Sold: 1,781,269
Publisher: Pan Macmillan
Genre: Picture Books

Book Name: Jamie's 30-Minute Meals
Author Name: Oliver, Jamie
Volumes Sold: 1,743,266
Publisher: Penguin
Genre: Food & Drink: General

Book Name: Kite Runner,The
Author Name: Hosseini, Khaled
Volumes Sold: 1,629,119
Publisher: Bloomsbury
Genre: General & Literary Fiction

Book Name: One Day
Author Name: Nicholls, David
Volumes Sold: 1,616,068
Publisher: Hodder & Stoughton
Genre: General & Literary Fiction

Book Name: Thousand Splendid Suns,A
Author Name: Hosseini, Khaled
Volumes Sold: 1,583,992
Publisher: Bloomsbury
Genre: General & Literary Fiction

Book Name: Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy
Author Name: Larsson, Stieg
Volumes Sold: 1,555,135
Publisher: Quercus
Genre: Crime, Thriller & Adventure

Book Name: Time Traveler's Wife,The
Author Name: Niffenegger, Audrey
Volumes Sold: 1,546,886
Publisher: Random House
Genre: General & Literary Fiction

Book Name: Atonement
Author Name: McEwan, Ian
Volumes Sold: 1,539,428
Publisher: Random House
Genre: General & Literary Fiction

Book Name: Bridget Jones's Diary:A Novel
Author Name: Fielding, Helen
Volumes Sold: 1,508,205
Publisher: Pan Macmillan
Genre: General & Literary Fiction

Book Name: World According to Clarkson,The
Author Name: Clarkson, Jeremy
Volumes Sold: 1,489,403
Publisher: Penguin
Genre: Humour: Collections & General

Book Name: Captain Corelli's Mandolin
Author Name: Bernieres, Louis de
Volumes Sold: 1,352,318
Publisher: Random House
Genre: General & Literary Fiction

Book Name: Sound of Laughter,The
Author Name: Kay, Peter
Volumes Sold: 1,310,207
Publisher: Random House
Genre: Autobiography: General

Book Name: Life of Pi
Author Name: Martel, Yann
Volumes Sold: 1,310,176
Publisher: Canongate
Genre: General & Literary Fiction

Book Name: Billy Connolly
Author Name: Stephenson, Pamela
Volumes Sold: 1,231,957
Publisher: HarperCollins
Genre: Biography: The Arts

Book Name: Child Called It,A
Author Name: Pelzer, Dave
Volumes Sold: 1,217,712
Publisher: Orion
Genre: Autobiography: General

Book Name: Gruffalo's Child,The
Author Name: Donaldson, Julia
Volumes Sold: 1,208,711
Publisher: Pan Macmillan
Genre: Picture Books

Book Name: Angela's Ashes:A Memoir of a Childhood
Author Name: McCourt, Frank
Volumes Sold: 1,204,058
Publisher: HarperCollins
Genre: Autobiography: General

Book Name: Birdsong
Author Name: Faulks, Sebastian
Volumes Sold: 1,184,967
Publisher: Random House
Genre: General & Literary Fiction

Book Name: Northern Lights:His Dark Materials S.
Author Name: Pullman, Philip
Volumes Sold: 1,181,503
Publisher: Scholastic Ltd.
Genre: Young Adult Fiction

Book Name: Labyrinth
Author Name: Mosse, Kate
Volumes Sold: 1,181,093
Publisher: Orion
Genre: General & Literary Fiction

Book Name: Harry Potter and the Half-blood Prince
Author Name: Rowling, J.K.
Volumes Sold: 1,153,181
Publisher: Bloomsbury
Genre: Science Fiction & Fantasy

Book Name: Help,The
Author Name: Stockett, Kathryn
Volumes Sold: 1,132,336
Publisher: Penguin
Genre: General & Literary Fiction

Book Name: Man and Boy
Author Name: Parsons, Tony
Volumes Sold: 1,130,802
Publisher: HarperCollins
Genre: General & Literary Fiction

Book Name: Memoirs of a Geisha
Author Name: Golden, Arthur
Volumes Sold: 1,126,337
Publisher: Random House
Genre: General & Literary Fiction

Book Name: No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.
Author Name: McCall Smith, Alexander
Volumes Sold: 1,115,549
Publisher: Little, Brown Book
Genre: Crime, Thriller & Adventure

Book Name: Island,The
Author Name: Hislop, Victoria
Volumes Sold: 1,108,328
Publisher: Headline
Genre: General & Literary Fiction

Book Name: PS, I Love You
Author Name: Ahern, Cecelia
Volumes Sold: 1,107,379
Publisher: HarperCollins
Genre: General & Literary Fiction

Book Name: You are What You Eat:The Plan That Will Change Your Life
Author Name: McKeith, Gillian
Volumes Sold: 1,104,403
Publisher: Penguin

In [38]:
driver.quit()

8. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/ You
have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute G) Year
 Note: - from the home page you have to go to the Show All Dataset page through code.

In [39]:
driver=webdriver.Chrome()

In [40]:
driver.get("https://archive.ics.uci.edu/")

In [42]:
datasets=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]')
datasets.click()

In [51]:
dnametags=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
dnames=[]
for i in dnametags:
    dnames.append(i.text.strip())
dtypes=[]
dtypetags=driver.find_elements(By.XPATH,'//div[@class="my-2 hidden gap-4 md:grid grid-cols-12"]/div[2]/span')
for i in dtypetags:
    dtypes.append(i.text.strip())
tasks=[]
tasktags=driver.find_elements(By.XPATH,'//div[@class="my-2 hidden gap-4 md:grid grid-cols-12"]/div[1]/span')
for i in tasktags:
    tasks.append(i.text.strip())
instances=[]
instags=driver.find_elements(By.XPATH,'//div[@class="my-2 hidden gap-4 md:grid grid-cols-12"]/div[3]/span')
for i in instags:
    instances.append(i.text.strip(""))
attributes=[]
attritags=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/div[1]/main/div/div[2]/div[2]/div[1]/div[1]/div[2]/svg')
for i in attritags:
    attributes.append(i.text.strip(""))

In [53]:
df=pd.DataFrame({'Name':dnames,'Task':tasks,'No. of instances':instances,'No. of attributes':attributes,'Datatype':dtypes})
df

,Name,Task,No. of instances,No. of attributes,Datatype
0,Iris,Classification,150 Instances,4 Features,Tabular
1,Dry Bean,Classification,13.61K Instances,16 Features,Multivariate
2,Heart Disease,Classification,303 Instances,13 Features,Multivariate
3,Rice (Cammeo and Osmancik),Classification,3.81K Instances,7 Features,Multivariate
4,Adult,Classification,48.84K Instances,14 Features,Multivariate
5,Raisin,Classification,900 Instances,8 Features,Multivariate
6,Breast Cancer Wisconsin (Diagnostic),Classification,569 Instances,30 Features,Multivariate
7,Wine,Classification,178 Instances,13 Features,Tabular
8,Wine Quality,"Classification, Regression",4.9K Instances,12 Features,Multivariate
9,Diabetes,Classification,1 Instances,20 Features,"Multivariate, Time-Series"

In [54]:
driver.quit()